"""empty message

Revision ID: 2da868899e1c
Revises: 80450b417e9d
Create Date: 2020-12-13 13:19:03.015843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da868899e1c'
down_revision = '80450b417e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'reservation', ['name'])
    op.drop_column('reservation', 'listed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('listed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reservation', type_='unique')
    op.drop_column('reservation', 'name')
    # ### end Alembic commands ###
