"""empty message

Revision ID: 5490a95870c7
Revises: 2da868899e1c
Create Date: 2020-12-13 13:45:05.979712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5490a95870c7'
down_revision = '2da868899e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('is_listed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'is_listed')
    # ### end Alembic commands ###
