"""empty message

Revision ID: 6e8f4aa5056d
Revises: 5490a95870c7
Create Date: 2020-12-13 14:30:58.906608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8f4aa5056d'
down_revision = '5490a95870c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('is_listed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'is_listed')
    # ### end Alembic commands ###
